apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientui-deployment
  labels:
    app: clientui
    group: mcommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientui
  template:
    metadata:
      labels:
        app: clientui 
        group: mcommerce
    spec:
      containers:
      - name: clientui
        image: enoch180/clientui:1.0
        ports:
        - containerPort: 4000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: clientui-service
  group: mcommerce
spec:
  selector:
    app: clientui 
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 4000
