apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clientui
  name: clientui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientui
  template:
    metadata:
      labels:
        app: clientui
    spec:
      containers:
      - image: enoch180/clientui:1.0
        name: clientui
        ports:
        - containerPort: 4000
