apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientui
  labels:
    app: clientui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientui
  template:
    metadata:
      labels:
        app: clientui
    spec:
        containers:
        - name: container-clientui
          image: enoch180/clientui:1.0
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "development"
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: clientui-service
  labels: 
    group: mcommerce
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: clientui
  ports:
    - port: 8000        # port exposed outside ClusterIP
      targetPort: 8000    # port exposed by Pod
