---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: clienui-app
  namespace: default
  labels:
    app: clientui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientui-app
  template:
    metadata:
      labels:
        app: clientui-app
    spec:
      containers:
      - name: clientui-app
        image: "enoch180/clientui:1.0"
        ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: clientui-app
  namespace: default
spec:
  selector:
    app: clientui-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 4000
    port: 80
